language: node_js
dist: trusty
sudo: false
node_js:
- lts/*
services:
- docker
before_script:
# Prepare cross-compiling environment if targeting ARM
- if [ "$TARGET" == "raspberrypi3" ]; then docker run --rm --privileged multiarch/qemu-user-static:register --reset; fi
# Build the Docker image
- cd gateway
- docker build -t "${DOCKER_IMAGE}:latest" -f $DOCKER_FILE .
- docker tag "${DOCKER_IMAGE}:latest" "${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER}"
- cd ../
script:
# Test the gateway
- cd gateway
- npm ci
- cd ../
deploy:
  -
    provider: script
    script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push "$DOCKER_IMAGE" && docker push "${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER}"
    on:
      branch: master
matrix:
  include:
  - env: TARGET=raspberrypi3 DOCKER_IMAGE=lightelligenceio/olt-gateway-lite-rpi3 DOCKER_FILE=Dockerfile-raspberrypi3
    sudo: true
