language: node_js
dist: trusty
sudo: false
node_js:
- lts/*
services:
- docker
before_script:
- if [ "$TARGET" == "raspberrypi3" ]; then docker run --rm --privileged multiarch/qemu-user-static:register
  --reset; fi
- cd gateway
- docker build -t "${DOCKER_IMAGE}:latest" -f $DOCKER_FILE .
- docker tag "${DOCKER_IMAGE}:latest" "${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER}"
- cd ../
script:
- cd gateway
- npm ci
- cd ../
deploy:
- provider: script
  script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push
    "$DOCKER_IMAGE" && docker push "${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER}"
  on:
    branch: master
matrix:
  include:
  - env: TARGET=raspberrypi3 DOCKER_IMAGE=lightelligenceio/olt-gateway-lite-rpi3 DOCKER_FILE=Dockerfile-raspberrypi3
    sudo: true
env:
  global:
  - secure: luk+BTnPr+PLie09n7aifsmMMzfn5UL0TzQ7AyPgh0W6ks962mdytGdpbXOtg+JeHKJrqCkqgFyFhKipTwrggP3WSs8nh4s52Qz8jxzwClMSTMRRPPRxscUtlreFwszpjfGawOUH4TWVOYM2yXJ4se3lb7OsCB5SZ1/4CtQYzokRzegXi/9rnW9Ce3LVlPInOor3xRLkX7HYmny4wRTJ9JMtu46Ku2G3vgk2iYWGAjZd+Twb3OmC5lamBEqL5uLEhneRYemcwFIpLMNdKdj7GEw2SLhkBpam+viweUvKqZvdgUaz1yoVzGj/Qs7kkiKRO3k34/BZiZJQzyL1zipRGp2bz0xBTNtsHwDLbHyQyFa14FODPFpCcRbj/0tmX6JXsLFFMVelztDxvvUy+j4yCpb54xSL4J8vWZhDoMeiIgjEHb5aO1KG8t1VD7nxrmQyovJPiElFksOoSidqsNXsXOjlI+FpGOTNYu9561/Z71M7wWDPbZEvtRaeKBLRKYH6ydGMu2kT50aKK0ULLNHRW5khnc0wfI33+XI7wtd4KmcsBJQKa1pzMDhQEpt/xqxD0WnFwbmEQe60qjVLGwWvGWG5KGYvT5aVWfqWEVm0W94ZfaBuXoSMwzKFyx1Kgt3iSqQSPUt7eIgMUbLcqZ449d2lmPdcCX0keWB4YnNjjYQ=
  - secure: ek33/LuI4tSt3zdZPA4+hoRcLpJVNkaRV0npmQY3mbDPLgFTExapF4e1tGyFr4SMOOo/gOyVz96A3Kin1CH3+MQE8AA4q6r2YoJ8E3K5BK8MoZMD0zwVY4sS1jwl4dokvY0UypSunLEXhSRYbOVGAVAA7RL2pkn75tsze5VD37SaKmW0ql81s8CSf3rDaIc0xzVlZ6q1CNK+FzSverQTqutySJq4mCcuU0l+4QW/6A6whFqRWQLHpFiAPggIpQ/7aSl58H3i3Fls+rX1nYfF/0ArWS9wxkC82M6UDiNmPTm1q5piAjFXmGcbIfr0YtwAEHz6XDagmPoAhxz9TZkMvB4fzY40m91xi/1He2thaVMqZOAUL7dkldpo50RNFKcHOP+0j1IAgpuErjVdayyuCSHvsSqtdm0T/OMSgbWTBmKUBAqKRErfRwGg4K8jsRAOceCz51Kux81ytZx0C3fNmNY++eqwstYnteeiP6DITPew4oXdw+aiEoC9FpAGUFvKfKfZvvdQCTRcvZQTQAm/YApwI5qhgFu6jASOWHKtMOYtplkclig62y5e0YqsajfkXxEidheXooHU8zKG0UqMI9V5gxWK0tRbYsdegF9zPD6kdBfXF1elTThHrT9QGaTKhbFLn6w4yDICiZV1eLYnT5hUFMUvFPw0o3Lgvcwq9EE=
