language: node_js
dist: trusty
sudo: false
node_js:
- lts/*
services:
- docker
before_script:
- if [ "$TARGET" == "raspberrypi3" ]; then docker run --rm --privileged multiarch/qemu-user-static:register
  --reset; fi
- cd gateway
- docker build -t "${DOCKER_IMAGE}:latest" -f $DOCKER_FILE .
- docker tag "${DOCKER_IMAGE}:latest" "${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER}"
- cd ../
script:
- cd gateway
- npm ci
- cd ../
deploy:
- provider: script
  script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push
    "$DOCKER_IMAGE" && docker push "${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER}"
  on:
    branch: master
matrix:
  include:
  - env: TARGET=raspberrypi3 DOCKER_IMAGE=lightelligenceio/olt-gateway-lite-rpi3 DOCKER_FILE=Dockerfile-raspberrypi3
    sudo: true
env:
  global:
  - secure: YrZ13hpzGCLsk+Gqwi2amiFwaFd8KLdNVSy1uLUqo9D1LsOLaWYSnlm99UMpxapOIpsxOACaLxYvB6S3f+o2I73xGOhsQXsS3pVu1tGulq7Tw33vQxAeCD6K3bhcmaEF1GPnjs7lEy5+HqetvEIpSToVgte2aAj/32apAWTdYtUpIg6O5Qhwyd1gKbtthAx8Qf2rK9yNKmggFeLbORKV3zOHkCOoOGJVNlS1mDlcspGpE8mdx/MkmWzvWFWTAef5Xs7L7XaKmZYmlUR699OC36hf2cUVIy/k18Pr2aim013oClKOf/tpvvsJWVwS7yOtq7V6ug31YRwHq026e4e9Zx2yBMfJGKtwzebgkK84ohchJNGD5FTI/Kub4DM7RhQJl9hENKWiORqhAVbTh+Ne6FXaYkZpgFfZ0qUPjfU9cjKwXVVT9nEX2q3TfJr2daTR6gB5Nb7PiZY3xOE+pHsmSlYSXuDOiUjH5dRYyLpWxu2vcjaKwbO3q3wAgY86O9IjBx9JY5cUWHZL88owTLz62Ngp3hdXChnPBXUNleu9/5HX1McMcVRRxHUR1soFK1nzuKhPLffKS+iFfm9+TzgRXqH74MKjKZJ6RungeU/wBk1XdwKzF2VYRAtUnSXX9ZfHlW0bLGEjVm1y4xsIBBsvfvnw5YcmPG1vKV8R7kVKNZg=
  - secure: luk+BTnPr+PLie09n7aifsmMMzfn5UL0TzQ7AyPgh0W6ks962mdytGdpbXOtg+JeHKJrqCkqgFyFhKipTwrggP3WSs8nh4s52Qz8jxzwClMSTMRRPPRxscUtlreFwszpjfGawOUH4TWVOYM2yXJ4se3lb7OsCB5SZ1/4CtQYzokRzegXi/9rnW9Ce3LVlPInOor3xRLkX7HYmny4wRTJ9JMtu46Ku2G3vgk2iYWGAjZd+Twb3OmC5lamBEqL5uLEhneRYemcwFIpLMNdKdj7GEw2SLhkBpam+viweUvKqZvdgUaz1yoVzGj/Qs7kkiKRO3k34/BZiZJQzyL1zipRGp2bz0xBTNtsHwDLbHyQyFa14FODPFpCcRbj/0tmX6JXsLFFMVelztDxvvUy+j4yCpb54xSL4J8vWZhDoMeiIgjEHb5aO1KG8t1VD7nxrmQyovJPiElFksOoSidqsNXsXOjlI+FpGOTNYu9561/Z71M7wWDPbZEvtRaeKBLRKYH6ydGMu2kT50aKK0ULLNHRW5khnc0wfI33+XI7wtd4KmcsBJQKa1pzMDhQEpt/xqxD0WnFwbmEQe60qjVLGwWvGWG5KGYvT5aVWfqWEVm0W94ZfaBuXoSMwzKFyx1Kgt3iSqQSPUt7eIgMUbLcqZ449d2lmPdcCX0keWB4YnNjjYQ=
