FROM arm32v7/node:10

ENV NPM_CONFIG_LOGLEVEL warn
ENV NODE_ENV production
ENV SOURCES /app

COPY . ${SOURCES}
WORKDIR ${SOURCES}

RUN chown -R node:node ${SOURCES}
USER node

RUN npm ci --production --quiet

CMD npm start
