FROM resin/raspberrypi3-node:8

ENV NPM_CONFIG_LOGLEVEL warn
ENV NODE_ENV production
ENV SOURCES /app

RUN mkdir ${SOURCES}
COPY . ${SOURCES}

WORKDIR ${SOURCES}
VOLUME /app/certs

RUN npm install --only=production

CMD npm start
